version: "3.7"

networks:
  loki:

services:
  loki:
    image: grafana/loki:master
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:master
    deploy:
      mode: global
      resources:
        reservations:
          cpus:   '0.10'
          memory: '16M'
        limits:
          cpus:   '0.10'
          memory: '32M'

    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/docker-config.yaml
    configs:
    - source: promtail-config
      target: /etc/promtail/docker-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    networks:
      - loki
configs:
  promtail-config:
    file: ./promtail-config.yml
