services:
  db:
    image: "mariadb:11.4.2"
    environment:
    - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=jaj
    restart: always
    healthcheck:
      test: ls /run/mysqld/mysqld.sock
    networks:
    - mynetwork
    volumes:
    -  database:/var/lib/mysql
  mysqlexporter:
    image: "prom/mysqld-exporter:v0.15.1"
    environment:
    - "collect.perf_schema.eventsstatements"
    - "collect.perf_schema.eventsstatementssum"
    command:
    - "--mysqld.username=root"
    - "--mysqld.address=db:3306"
    networks:
      - mynetwork
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
  
  loader:
    image: "erkules/mariadbclient:10.11.6"
    command:
    - sh
    - -c
    - "mysql -h db </srv/load.sql"
    depends_on:
      db:
        condition: service_healthy
    volumes:
    - ./load.sql:/srv/load.sql
    networks:
    - mynetwork

  apache:
    image: "erkules/webhookimg:v4"
    volumes:
    - ./index.html:/usr/local/apache2/htdocs/index.html
    - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
    - 8080:80
    networks:
    - mynetwork

  apacheexporter:
    image: "bitnami/apache-exporter"
    command: --scrape_uri="http://apache/server-status/?auto"
    networks:
    - mynetwork
    
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
    - ./prometheus:/etc/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
    - "9090:9090"
    networks:
    - mynetwork
  grafana:
    image: grafana/grafana:latest
    ports:
    - "3000:3000"
    networks:
      - mynetwork
    volumes:
    - ./provisioning:/etc/grafana/provisioning

networks:
  mynetwork:
volumes:
  database:
    name: db
