version: "3"
services:
  portainer:
    image: portainer/portainer
    command:
    - -H
    - unix:///var/run/docker.sock
    ports:
    - 9080:9000
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
