groups:
- name: generic.rules
  rules:
  - alert: ServiceDown
    expr:  up == 0
    for:   1m
    annotations:
      summary:     "Service {{ $labels.job }} on  {{ $labels.instance }} down"
      description: "{{ $labels.instance }} or job {{ $labels.job }} has been down for more than 5m"
    labels:
      severity: pipapolopo
  
  - alert: ImAlive
    expr:  vector(1)
    for:   1m
    annotations:
      summary:     "Prometheus is alive"
      title:       "Prometheus is alive"
      text:        "Prometheus is alive"
  - alert: FileSystemFull
    expr:  1-node_filesystem_free{mountpoint="/rootfs"}/node_filesystem_size{mountpoint="/rootfs"} >0.8
    for:   5m
    annotations:
      title:       "Filesystem is over 80% ( {{ $value }} )"
      summary:     "Filesystem is over 80% ( {{ $value }} ) on node {{ $labels.instance }}"
      text:        "Filesystem is over 80% ( {{ $value }} ) on node {{ $labels.instance }}"
  
  - alert: FileSystemFullIn4h
    expr:  predict_linear(node_filesystem_free{mountpoint="/rootfs"}[1h],4 * 3600) < 0
    for:   5m
    annotations:
      title:       "Filesystem is full in at least 4h"
      summary:     "Filesystem is full in at least 4h on node {{ $labels.instance }}"
      text:        "Filesystem is full in at least 4h on node {{ $labels.instance }}"
  
  - alert: FileSystemInodesFull
    expr:  1-node_filesystem_files_free{mountpoint="/rootfs"}/node_filesystem_files{mountpoint="/rootfs"} >0.8
    for:   5m
    annotations:
      title:       "Running low on Inodes"
      summary:     "Running low on Inodes on node {{ $labels.instance }}"
      text:        "Running low on Inodes on node {{ $labels.instance }}"
  - record:  node_load5:divided_by_cpu:5m
    expr:    node_load5/count(node_cpu{mode="idle"}) without (cpu,mode)
  - alert: HighLoad5m
    expr:  node_load5:divided_by_cpu:5m > 1
    for:   5m
    annotations:
      title:       "High Load"
      summary:     "High Load on node {{ $labels.instance }}"
      text:        "High Load on node {{ $labels.instance }}"
       
