global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqlexporter:9104']


  - job_name: 'apache'
    static_configs:
      - targets: ['apacheexporter:9117']

