version: '3.1'

services:
  minio1:
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z.hotfix.65162d087
    volumes:
      - minio-data:/export
    ports:
      - "9000:9000"
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server /export
    secrets:
      - secret_key
      - access_key
secrets:
  secret_key:
    file: ./secret_key.txt
    #external: true
  access_key:
    file: access_key.txt
    #external: true
volumes:
  minio-data:
